color = [
    "black",
    "blue",
    "red",
    "orange",
    "green",
    "magenta",
    "grey",
    "white",
    "snow",
    "old lace",
    "linen",
    "antique white",
    "papaya whip",
    "blanched almond",
    "bisque",
    "peach puff",
    "navajo white",
    "alice blue",
    "lavender",
    "lavender blush",
    "misty rose",
    "dark slate gray",
    "dim gray",
    "slate gray",
    "light slate gray",
    "gray",
    "light grey",
    "midnight blue",
    "navy",
    "cornflower blue",
    "dark slate blue",
    "slate blue",
    "medium slate blue",
    "light slate blue",
    "medium blue",
    "royal blue",
    "blue",
    "dodger blue",
    "deep sky blue",
    "sky blue",
    "light sky blue",
    "steel blue",
    "light steel blue",
    "light blue",
    "powder blue",
    "pale turquoise",
    "dark turquoise",
    "medium turquoise",
    "turquoise",
    "cyan",
    "light cyan",
    "cadet blue",
    "medium aquamarine",
    "aquamarine",
    "dark green",
    "dark olive green",
    "dark sea green",
    "sea green",
    "medium sea green",
    "light sea green",
    "pale green",
    "spring green",
    "lawn green",
    "medium spring green",
    "green yellow",
    "lime green",
    "yellow green",
    "RosyBrown1",
    "RosyBrown2",
    "RosyBrown3",
    "RosyBrown4",
    "IndianRed1",
    "IndianRed2",
    "IndianRed3",
    "IndianRed4",
    "sienna1",
    "sienna2",
    "sienna3",
    "sienna4",
    "burlywood1",
    "burlywood2",
    "burlywood3",
    "burlywood4",
    "wheat1",
    "wheat2",
    "wheat3",
    "wheat4",
    "tan1",
    "tan2",
    "tan4",
    "chocolate1",
    "chocolate2",
    "chocolate3",
    "firebrick1",
    "firebrick2",
    "firebrick3",
    "firebrick4",
    "brown1",
    "brown2",
    "brown3",
    "brown4",
    "salmon1",
    "salmon2",
    "salmon3",
    "salmon4",
    "LightSalmon2",
    "LightSalmon3",
    "LightSalmon4",
    "orange2",
    "DarkOrange1",
    "DarkOrange2",
    "DarkOrange3",
    "DarkOrange4",
    "coral1",
    "tomato2",
    "OrangeRed2",
]
